sudo: false
language: java

# skip default "install" command
install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # -x taskName could be used to skip a task
    - GRADLE_OPTS="-Djava.awt.headless=true"

matrix:
  include:
    - name: Tests with OpenJDK 8
      jdk: oraclejdk8
      script:
          - ./gradlew $GRADLE_OPTS check createDist jacocoReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
